cyclosm/cyclosm-cartocss-style

roads.mss

Lighter cycle route rendering, cycleway in full line and cycle lane/shared busway in dash line

---

README.md
road-colors-generated.mss
road-colors.yml
roads.mss

(don't look at the surface rendering by axial dash line).

Render pedestrian as a street

---

CONTRIBUTING.md
INSTALL.md
base.mss
palette.mss
project.mml

http://localhost:6789/cyclosm-cartocss-style/#10/45.7699/3.3028
http://localhost:6789/cyclosm-cartocss-style/#13/45.8645/3.5615
http://localhost:6789/cyclosm-cartocss-style/#13/45.6298/2.8312

Rework colors, darken a bit the palette after hillshades merge

---

base.mss
palette.mss
project.mml
roads.mss

Contours bigger in high zoom, Draw two way cycleway wider, fix steps

---

roads.mss

- 2 less road outline render
- cycleway= use same width than highway=cycleway

Change cycleway= rendering

---

road-colors-generated.mss
road-colors.yml
roads.mss

Fix misleading color for path and better track color, fix width for service and track roads

---

amenities.mss
palette.mss
project.mml
road-colors-generated.mss
road-colors.yml

Lighter farmland and meadow, fade footway/bridleway, lower zoom for crossing and traffic calming

---

CHANGELOG.md
project.mml

Fix https://github.com/cyclosm/cyclosm-cartocss-style/issues/180.

No longer render tunnel waterways.

---

project.mml
road-colors-generated.mss
road-colors.yml
roads.mss

fix most of #138 
May be we need to fix the outline of main road and path (too faded) and some other tweaking, but overall the render is a good improvement imho.

Fill in grey road without bicycle access

---

palette.mss
roads.mss

This gives a better feeling for the relations between roads. Should mostly solve #277.
Before 
After

Give bridges for large roads a dark border on zoom >= 14

---

amenities.mss
project.mml
symbols/openstreetmap-carto/amenity/charging_station.svg

Remove useless test for motorcycle_parking (data is already filter by the where before).
Fix #290

Add bicycle charging station amenity.

---

base.mss
palette.mss
project.mml

Fix #303 
City wall:
Hedge:
fence, retaining wall:

Add barriers line

---

scripts/render_single_tile.py

From https://github.com/giggls/openstreetmap-carto-de/blob/master/scripts/render_single_tile.py

Add script for rendering a tile, can be use for testing the perf also.

---

.gitignore
scripts/test/test_zooms.sh

Add a test script to render 21 zooms of a tile and save the render times for each.
Can be used for regression test.

Add a test script to render 21 zooms of a tile and save the render times for each.

---

project.mml

Fix ferry route over name labels in low zooms.

---

labels.mss
project.mml

Fix ref not rendered for trunk and motorway.

---

labels.mss
palette.mss
project.mml

Add conditional text along the way for bicycle|vehicle|access|motor_vehicle:conditional

---

project.mml
road-colors-generated.mss
road-colors.yml
roads.mss

Railway at low zooms

---

roads.mss

link to #215 
I didn't add bridleway because I'm not confident in doing so.
And if do so, we should do in the sql request the merge into one type path_designated (and path)
+Fix a missing surface rendering for path or footway bicycle=designated.
Please if I didn't forget or break something.

Render footway+bicycle=designated as a shared path (light blue).

---

project.mml
roads.mss

And refactor footway/bridleway + bicycle=designated|yes as path in sql.
fix #215

Render bridleway+bicycle=designated as a shared path.

---

project.mml
roads.mss

So we this can hide useless footways for cyclist (like subway tunnels).
I wonder if we could also use tags indoor and level for that

Lighten footway color in tunnel

---

admin.mss
palette.mss

Darken borders, specialy for the states. They were difficulte to see.

---

amenities.mss
labels.mss
project.mml
road-colors.mss
roads.mss

(branch from optim-roads.mss)
Should fix #359

Labels zoom

---

docs/INSTALL.md

The contributing.md file is in the root folder and in the `docs` one.

Update the path to the contributing file.

---

scripts/docker-startup.sh

Hello,
I managed to run cyclosm docker but I had to change import script : osm data is imported to 'gis' database, but kosmtik is expecting 'osm' database

docker import to "osm" database

---

base.mss
project.mml
road-colors.mss

Footway area is rendered in light brown color :
Should close #370

render brownish footway area

---

CHANGELOG.md
amenities.mss

Fix bicycle shop size

---

amenities.mss

Bicycle service sub icons are only set for some POI (convenience/supermarket, parking, fuel, repair station, bicycle shop, sport shop).
Was at 57s on my PC, to 14s with this fix.

Optim time to generate xml due to a regression with subicons

---

CHANGELOG.md
project.mml

Here is a fix #266.
Some typical such ways:
```
osm_id   | highway  | maxspeed
-----------+----------+----------
445114686 | cycleway | 30
445114675 | cycleway | 30
445114660 | cycleway | 30
445114681 | cycleway | 30
445114663 | cycleway | 30
445114684 | cycleway | 30
445114688 | cycleway | 30
445114669 | cycleway | 30
445114665 | cycleway | 30
445114659 | cycleway | 30
445114677 | cycleway | 30
445114674 | cycleway | 30
445114682 | cycleway | 30
445114661 | cycleway | 30
445114690 | cycleway | 30
445114687 | cycleway | 30
445114672 | cycleway | 30
445114676 | cycleway | 30
470444407 | track    | 50
470444431 | track    | 50
371397795 | track    | 50
662299027 | track    | 15
688447369 | track    | 10
688447382 | track    | 10
240241071 | track    | 25
227130854 | track    | 25
240388642 …
```

Render maxspeed on shared path, see #266.

---

CHANGELOG.md
amenities.mss
project.mml
roads.mss
symbols/openstreetmap-carto/amenity/parking.svg

Hidden and thiner minor service road

---

amenities.mss
project.mml
symbols/amenity/xmas_tree.svg
symbols/openstreetmap-carto/shop/marketplace.svg

I had time to loose 🎅
Only rendered after 15 of December.

Add xmas tree and market at the end of December.

---

base.mss
project.mml

Didn't test hillshading, I hope it can work :)
fix #493 
Test, argentina in z3 and 4, without hillshading :

Render land, water and hillshade at zoom 3 and 4.

---

CHANGELOG.md
project.mml

Render dam like buildings.

---

CHANGELOG.md
project.mml

Add tracktype=grade1 and good smoothness as road bike surfaces.

---

CHANGELOG.md
project.mml

Fix ford on node not rendered.

---

CHANGELOG.md
labels.mss
project.mml

Fix bicycle route name not rendered if no ref

---

CHANGELOG.md
roads.mss

Fix #356 see pictures example in the ticket.

Use shared blue for cycle lane and bus lane.

---

CHANGELOG.md
base.mss
palette.mss
project.mml
roads.mss

Superseeds #472 (started from the same code base). @Florimondable please merge this one if render is ok for you.
Screenshots : (only layers are landuse and leisure_track)
http://localhost:6789/cyclosm-cartocss-style/#19/47.20938/-1.51680
http://localhost:6789/cyclosm-cartocss-style/#19/48.82544/2.48265
http://localhost:6789/cyclosm-cartocss-style/#18/48.82623/2.41265
http://localhost:6789/cyclosm-cartocss-style/#19/47.22952/-1.59251

Leisure=track and areas

---

CHANGELOG.md
roads.mss

fix #519 
Render a thin grey line at zoom 14.

Render minor service road at zoom 14.

---

amenities.mss
project.mml

Fix #528
https://www.cyclosm.org/#map=20/48.87775/2.36550/cyclosm_live
**Was: **
**Becomes:**
https://www.cyclosm.org/#map=20/48.83984/2.34750/cyclosm_live
**Was:**
**Becomes:**

Improve clpc rendering

---

CHANGELOG.md
project.mml

Render train stations when tagged on buildings (polygons)

---

project.mml

I did use the same filter for the riverbank adding only dock.

Add waterway = dock

---

CHANGELOG.md
project.mml

Rendering bridge surface like a building. Fix #551

---

CHANGELOG.md
roads.mss

Remove rendering of ramp separate

---

amenities.mss
symbols/osmfr/aed2.svg
views.sql

Fix #496
Render defibrillators from Z19, just the same way as `emergency=phone` were rendered.

Render defibrillators

---

CHANGELOG.md
amenities.mss

Render aerodrome icons at higher zoom levels, see #564.

---

roads.mss

Adresses issue https://github.com/cyclosm/cyclosm-cartocss-style/issues/666

Prevent cyclestreets without cars from rendering as pedestrian streets
