palette.mss
project.mml
roads.mss

Steps have it own style, with bicycle ramp.
Cycle style doesn't depend on pedestrian anymore.
Cycle is bigger around Z11-15.
In this image you have steps (upper) and other steps with a bicycle ramp (lower).

Steps, bicycle ramp, and bigger cycleway.

---

project.mml
roads.mss

@Florimondable This is changing quite a lot of lines of code for the render of tunnels and bridges. I did some checks in places I know, but I could definitely use a second pair of eyes on this. Could you check that the render is the same as the current one for bridges and tunnels you are familiar with? Thanks!
Compiling the project to a Mapnik XML file was taking a lot of time,
mainly due to the tunnel and bridge layers. Here are some fixes to
improve compilation time.
* Use attachments for tunnels and bridges instead of selecting all the
data three times from the database and filtering on it.
* Rework the filtering in `roads.mss` file to avoid having too many
levels of imbrication, responsible for a lot of overhead at compilation.
* Remove the upper zoom limit as there is no reason to …

Rework the tunnel and bridge layers for better performance

---

labels.mss

Should fix https://github.com/cyclosm/cyclosm-cartocss-style/issues/101.
@Florimondable I'd need a double check on this one :)

Oneway arrow should be grey when oneway for all vehicles. Fix #101

---

project.mml
roads.mss

After merging #113, the compilation time became very long (about 10s for each road layer).
This should improve this and simplify a bit the data model. I'm now only using one cycleway variable for each side:
* `cycleway_{left,right}` contains the left (right) cycleway value (or the `cycleway` tag if no overloading is possible with side cycleway tag).
* `has_cycleway_{left,right}` is used as a boolean value to check whether the left (right) outline should be overloaded.
I gave a try and it should be ok. @Florimondable, might I ask you to have a look and double check I didn't mess up this change? Thanks!

Improve compilation time

---

labels.mss
project.mml
road-colors-generated.mss
road-colors.yml
roads.mss

link to #143 (but not completed yet, segregated must be done also)
Can't be able to fix the oneway arrow not rendered issue on path with _oneway:bicycle=yes_

Render path with bicycle=designated almost as a cycleway and segregated as a cycleway

---

amenities.mss
palette.mss

Fix #177 
Fix also a bug with the text not drawn with full opacity whereas the parking circle is transparent cause of limited actess.
Motorcycle-bicycle parking on the left
Text bug
Text fixed

Motorcycle-Bicycle parking in mixed blue

---

symbols/amenity/bicycle_motorcycle_parking_matrix.svg
symbols/amenity/bicycle_parking.svg
symbols/amenity/bicycle_parking_covered.svg
symbols/amenity/bicycle_parking_secured.svg
symbols/amenity/bicycle_parking_secured_covered.svg
symbols/amenity/motorcycle_parking.svg
symbols/amenity/motorcycle_parking_covered.svg
symbols/amenity/motorcycle_parking_secured.svg
symbols/amenity/motorcycle_parking_secured_covered.svg

Hello,
here is a rework of icon files for #226.

secured bicycle parking icon rework

---

project.mml

obligatoire pour que l'index géométrique soit utilisable !

ajout de "way && !bbox!" qd on ne renvoie pas directement "way"

---

base.mss
project.mml

Fixes https://github.com/cyclosm/cyclosm-cartocss-style/issues/270
The query missed military areas where both `military=...` and `landuse=military` are set. For example a military range with `landuse=military` and `military=range`. This feature would be picked up by the query, but not be styled on the map.
Example query for such data: https://overpass-turbo.eu/s/PSG
Before:
After

Make military areas visible even when both military and landuse are set

---

project.mml

This PR improves the cycling network visualization in The Netherlands and Belgium for any regional routes marked with `network:type = 'node_network'` (impact, see https://taginfo.openstreetmap.org/tags/network%3Atype=node_network#map)
Large improvement for issue #276.
- Don't include cycling network regional routes (node network type) for display on zoom levels 8 to 10
- Don't show cycling network regional routes (node network type) labels on any zoom level (the route names are not important, the nodes are).
Old 
New 
Old 
New 
Unchanged (except for the labels)

Do not show regional cycling network routes on zoom 8-10

---

project.mml

Fix #297.
There were null values in the query because not all ways have the tags in the query (of course...). And `null` is not `false` in SQL, but resolves the whole WHERE to `null`.
Zoom 8
Zoom 10
Zoom 8
Zoom 10

Fix null in 'not' in cycle route node query for zoom 8-10

---

project.mml

to #253 
First commit use smaller grid to avoid its bad effect of filling the grid even if there is only one node in it Which result in noisy pixels around the route and like the opposite effect of antialiasing, that make the route more aliased and bigger. Results are ok.
Second commit use of ST_Symplify in order to realy simply the geometry which result with less nodes on the ways and hence better line rendering not aliased. Good result.
_Performance has not been tested, I don't know how to do that._
Before:
SnapToGrid after first commit, bigger grid (256):
Symplify:

Try to fix noise bicycle route at low zooms

---

roads.mss

Add line-cap round for cycleway/path to avoid empty spaces

---

CHANGELOG.md
placenames.mss
project.mml

Here is an attempt at tackling #195. I find it not too bad in this area, but deserves more testing.
Village with population >= 1000 are shown at Z10 :
Village with population >= 500 are shown at Z11 :

Improve density of city names in countryside at Z10/Z11. Fix #195.

---

CHANGELOG.md
project.mml
roads.mss

mtb:scale is rendered with dashes with STS colors (with simple, double or triple dashes).
mtb:scale:imba is rendered with dots with IMBA colors (double diamond is double dot).
If both is present mtb:scale is used.
Rendered on path (foot/bridle/cycle/path), track, service roads, from zoom 15.
fix #336 
STS :
IMBA :
both (rare case) :

Render mtb scales on path

---

roads.mss

Problem on cities with many cycleways the cycleways take too much place/volume, see Amsterdam
Example with fix :

Smooth the transition between z11 and z13 on z12 for cycle path width.

---

labels.mss

Fix #304 
I didn't choose to draw a border dash line like shared busways or shared lanes because here it's the full road which is designate and bicycle=designated is not an infrastructure tag but an access (legal) tag.

Add blue arrows on designated roads.

---

project.mml
road-colors.mss
roads.mss

Result : building xml in 14s, 7,3Mo
Time rendering is also 10% lower, much less for z11-14
:)
Big improvements was :
remove 'road' type (make it as residential in sql)
Merge in sql can_bicycle=no|private. 
remove useless z11 inline zoom definition for minor roads
rewrite roads inline by type
**EDIT**: Closes #366.

Optimize roads.mss

---

.gitignore
Dockerfile
Dockerfile.db
Dockerfile.import
docker-compose.yml
docs/DOCKER.md
docs/INSTALL.md
scripts/docker-startup.sh
scripts/tune-postgis.sh

Taken from https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md
This guide makes setting up the database, mapnik, data and kosmtik much simpler, and without having to import data into the database running on the system.
See https://github.com/cyclosm/cyclosm-cartocss-style/blob/64461f470911da807bce852d5a8e106efabadeef/docs/DOCKER.md for textual documentation on getting started.

Add support for running the style with Docker(-compose)

---

project.mml
roads.mss

Fix Use lcn color by default if a unknown network is set.
Merge trunk(_link) with motorway(_link) (use can_bicycle to handle default).
Move segragated outline path to an other layer.
Refactor outline_right/left.
Remove oneway bus/cycle lane direction at z18.
Rewrite ::outline, faster xml generation.
Result : 5.3Mo XML, 13s gen on PC, vs 6.9Mo and 14s.
Rendering is faster, and faster in Z11/12/13 and close for higher zoom than in february :
```
Date:   Fri Feb 14 21:02:57 2020 +0100
git status: ## master...origin/master
z0 rendering time: 0.980446 seconds
z1 rendering time: 0.906853 seconds
z2 rendering time: 0.984499 seconds
z3 rendering time: 1.265270 seconds
z4 rendering time: 2.086033 seconds
z5 rendering time: 2.389341 seconds
z6 rendering time: 2.414125 seconds
z7 rendering time: …
```

Optim roads.mss 2

---

project.mml

bicycle=use_sidepath denotes that cycling on the main road is legally forbidden, and that cyclists *must* use the sidepath. So it makes sense to render the same as bicycle=no, since it's just a specialisation that hints routers to look for a separate cycleway.

Treat use_sidepath as no

---

roads.mss

Hi ! Here is a new minor cosmetic fix
I've notices turning circles contour line is always 1px width, but roads casing width increases at high zoom.
I changes this to make circles and residential roads share the same contour width.

turning_circle contour width

---

project.mml

Update tags->'motorcar' to just motorcar.
motorcar is defined as a top-level field in planet_osm_line, and so not actually available in tags. This was breaking the nomotor styling for roads with motorcar=no.
EDIT (@Phyks): Fix #406.

Fixes to the nomotor road style

---

base.mss
project.mml
roads.mss

Hello,
I noticed `leisure=track sport=cycling` are not rendered in cyclosm unless they are areas. But they can be ways : https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtrack
Here is a proposal : `leisure=track sport=cycling` rendered as cycleway, and `leisure=track sport!=cycling` rendered as a path
EDIT (@Phyks): Fix #279.

render leisure=track like path or cycleway

---

CHANGELOG.md
base.mss
ferry-routes.mss
project.mml

Hello here!
Here is a new pull request containing:
* Buildings layer rendered above water,  because today `building=houseboat` are hidden uder water
* Ferry routes layer rendered below cycling routes : Needed because ferry routes rendering contains a ˋ@waterˋ blue background trick. 
* Ferry routes now more blue (in ˋ@cycle-fill`) when they accept bicycles.

Houseboats and ferry routes

---

project.mml

LCN routes are often tagged with a simple `lcn=` tag on the ways, rather than with route relations, especially because they often aren't numbered/named. Other tiers of cycle routes are much-less-often tagged this way, see taginfo: [lcn](https://taginfo.openstreetmap.org/keys/lcn) [rcn](https://taginfo.openstreetmap.org/keys/rcn) [ncn](https://taginfo.openstreetmap.org/keys/ncn) [icn](https://taginfo.openstreetmap.org/keys/icn).
The most common value is `yes`, but the next most common is `proposed`, which should be rendered similarly to relation-based routes with `state=proposed`, presumably.

 Render lcn routes tagged on ways directly

---

project.mml

Promote cycleways / paths with bikes allowed to z_order 99 and other paths to 98. This ensures they always render on-top of roads at the same layer, even when those roads are also tagged with railway= and so get a +35 boost to their z_order (see https://github.com/openstreetmap/osm2pgsql/blob/a424919b7810922be5586d6e24cf25126b4557ad/src/tagtransform-c.cpp#L61 for this behaviour). 
Note that tram tracks are still drawn on-top of cycleways/paths, as are railroad tracks, even after this change. This fixes #431 .

Place cycleways and paths at top of z-order hierarchy

---

CHANGELOG.md
road-colors.mss

Shift the hue of the tracks from 214° (very close to the hue of mixed-cycle-fill, which is 217°) to 140° (matching the hue of nomotor-fill), while maintaining the lightness and saturation. For reference, the hue of path-fill is 170° and cycle-fill is 240°, so with this change there is a continuum from roads that are (mostly) closed to motor vehicles (greenest) through paths that are either allowed or designated for bikes, but not reserved, to dedicated cycleways (bluest).
The screenshots show a variety of backgrounds. I think the tracks are still quite visible even over forests, but it does stand out less there than the blue does. On other backgrounds (grass, farmland, plain) they are about the same.

Greener tracks

---

admin.mss
labels.mss
roads.mss

Hello,
I made rails more visible (for issue #403) by adding perpendicular hatches.
I changed protected areas contour (for issue #396)
and added maximum area size for their text display condition (for issue #375)
EDIT (@Phyks): Fix #403, fix #396, fix #375.

Rail and protected areas rework

---

project.mml

Hello,
Great to see last updates released, thank you!
But I have noticed a new issue : routes with `state='proposed'` are no more dotted.
Here is a fix

fix proposed route no more rendered with dashes

---

admin.mss
roads.mss

no more motorway :
Thinner cycle routes, and secondary are in orange color (case color), railway can be well distinguish :
Roads at Z11 are now visible :

Fix lowzooms : remove motorway, cycle routes transition, roads at z11

---

roads.mss

The condition for the motorway_link (and trunk_link) fill colour was the wrong way around, so that it was shown as cycleable unless bicycle=yes.
Fixes #452.

Fix bug in motorway_link colour

---

CHANGELOG.md
amenities.mss
palette.mss
symbols/openstreetmap-carto/amenity/drinking_water.svg
symbols/openstreetmap-carto/amenity/drinking_water_full.svg

* Rework drinking water icon
* Distinguish toilets with drinking water.
* Distinguish access for toilets and drinking water.
Fix #399 #454

Fix drinking water, toilets, acess

---

CHANGELOG.md
project.mml

Fix #381 
See https://www.cyclosm.org/#map=19/48.46640/-4.56664/cyclosm
Render is 
If we want to keep the actual render (which is good, in my opinion), we only have two options:
* Either we respawn our shield building script to generate the background shield in a variety of sizes and formats. Looking at the lcn_ref values from taginfo, I'm definitely not convinced this would be clean enough as the shield names can be arbitrarily long.
* Or we truncate the cycle junction name. My bet here is that non-numeric cycle junction names are likely places names. Hence, given the surroundings in the map, having just a few letters can disambiguate and make a nice render.

Truncate long cycle junction names.

---

CHANGELOG.md
labels.mss
palette.mss
project.mml

Render next to the road the name of the cycle route with the network color darkened.
From z16.
Shield are more spaced to compensate the density.
fix #433

Add cycle route name label

---

CHANGELOG.md
amenities.mss
project.mml
roads.mss
symbols/openstreetmap-carto/amenity/parking.svg

Fix of pull request #437 (should replace it).
Fix #372 and should fix also #162.  
Merged with master.
Render minor service roads from z15 like oneway arrow (so no more oneway arrow alone).
Render P icon later at z16 like other common amenities.
Optim style.

Render minor service roads

---

CHANGELOG.md
amenities.mss
symbols/amenity/bicycle_parking_notlockable.svg

Fix #268 
I made the choice of rendering specifically floor and ground slot bicycle parking.
Dash icon is used instead of half circle, it's more easy to distinguish.
I didn't make other icons (covered/secured) since we talking about only 1500 points.

Render floor and ground slot bicycle parking with a dash.

---

amenities.mss
placenames.mss
project.mml

Fix #474 
Use OSM Carto style, so island size is used to discrimate at which zoom to render.
Add also islet.
Names rendered only from z14, cause of using amenities layers.

Fix island names, draw them with amenities.

---

CHANGELOG.md
road-colors.mss
roads.mss

#fix #492 
The outline for bridges is also little wider.

Add dashline outline on path like way tunnels

---

CHANGELOG.md
roads.mss

fix  #451
It's little more noisier but I think it's ok :

Remove rail background at z<=11 to avoid them hidding cycleways.

---

CHANGELOG.md
roads.mss

Fix also pedestrian color with maxspeed higher than 30km/h.
fix #238

Render living street with 20km/h speed limit color by default.

---

CHANGELOG.md
project.mml
roads.mss

Remove railway with tag service=yard|siding|spur from z<13
Fade them from z13
Fix #559, didn't use usage tag, its seems not worth it, service take most of minor railways.

Remove and fade minor railway

---

views.sql

Note: I have very little knowledge of SQL, so I might not be able to include all feedback, but hopefully this is a good start?
(Based on the way `highway=raceway` was added, plus how `motorway`s are by default (just like `busway`) inaccessible for cyclists)

Proposal for a fix for highway=busway #557

---

aerialways.mss

Changes proposed in this pull request:
add magic_carpet to aerialways.mss, because it doesn't get rendered.
Magic Carpets are people movers in ski resorts. It's good to render them in biking maps for quick reference and they are obstacles in the mountain.
Test rendering with link to the example place:
https://www.cyclosm.org/#map=17/40.33043/-7.61274/cyclosm
In this place there is a not rendered magic carpet.

Add aerialway = magic_carpet to 

---

CHANGELOG.md
views.sql

Cycleways and paths without a oneway tag will now be rendered identically a path/cycleway with a oneway=no tag. Fxes #601
The following screenshot from around https://www.cyclosm.org/#map=18/50.73743/7.07980/cyclosm
Before:
After:

Add fallback values for oneway_bicycle to views.sql

---

base.mss
project.mml

Z9 was quite anomaly in terms of rendering time. It was taking much longer than Z8 and Z10 during pre-computation.
Dominant layer was landuse_gen0. It was using subpixel rendering for landuse, which is useful at very low zoom but seems to be safely discardable at Z9.
Also add checking of way geometries against bboxes to ensure correct usage of geospatial indexes in db.
See as well
https://github.com/gravitystorm/openstreetmap-carto/pull/2874 and https://github.com/gravitystorm/openstreetmap-carto/pull/3458#issuecomment-430873795.
See https://github.com/cyclosm/cyclosm-cartocss-style/issues/644.
```
+-----------+----------------+-----------------------+-----------------+---------------------------+---------+
| Time (ms) | #lines fetched |         Layer         | #fields fetched | Size …
```

Optimize Z9 rendering

---

project.mml

As per
https://github.com/cyclosm/cyclosm-cartocss-style/issues/660#issuecomment-1773789357:
* Remove the final dot in the truncation of cycle junction node names.
* Keep the final characters instead of the leading ones.
Fix #660

Unnecessary ending dot on node_network labels
